// frontend/src/App.vue
<script setup lang="ts">
import Sidebar from './components/Sidebar.vue';
import { authState } from './api/auth'; 
</script>

<template>
  <div class="flex flex-row w-screen h-screen bg-primary-light dark:bg-slate-900">
    <Sidebar v-if="authState.loggedIn"></Sidebar>
    <div class="flex-grow bg-white dark:bg-black dark:text-white rounded-tl-lg">
      <RouterView :key="$route.path"/>
    </div>
  </div>
</template>

// frontend/src/App.svelte
<script>
    import { QueryClient, QueryClientProvider } from "@tanstack/svelte-query";
    import Navbar from "./components/Navbar.svelte";
    import { Route } from "tinro"
    import Home from "./pages/Home.svelte";
  import Login from "./pages/Login.svelte";
  import { authState } from "./api/auth";
  import SiteInfo from "./pages/SiteInfo.svelte";

    const queryClient = new QueryClient()
</script>

<div class="dark:bg-slate-900 dark:text-white h-screen w-screen">
<QueryClientProvider client={queryClient}>
    {#if $authState}
    <div class="flex flex-col h-screen w-screen">
    <Navbar/>
    <Route path="/"><Home/></Route>
    <Route path="/sites/:id" let:meta><SiteInfo siteId={meta.params.id}/></Route>
    </div>
    {:else}
    <Login/>
    {/if}
</QueryClientProvider>
</div>
